language: ruby
sudo: false
script: "set -e && gem install github-pages && jekyll build"
rvm: 2.1
notifications:
    email: false
matrix:
    fast_finish: true
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
